# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rakuten_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rakuten_test
 pod 'SVProgressHUD'

  target 'Rakuten_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rakuten_testUITests' do
    # Pods for testing
  end

end
